import { ReservationResponse } from './reservationResponse';

export const defaultReservationResponse: ReservationResponse = {
  id: 0,
  camp_id: 0,
  property_id: 0,
  status: '',
  total_price: 0,
  deposit_amount: null,
  created_at: '',
  updated_at: '',
  camp_name: null,
  property_name: null,
  property_city: null,
  property_period: null,
  property_start_date: null,
  property_end_date: null,
  participant_first_name: null,
  participant_last_name: null,
  participant_age: null,
  participant_gender: null,
  participant_city: null,
  parents_data: null,
  invoice_type: null,
  invoice_first_name: null,
  invoice_last_name: null,
  invoice_email: null,
  invoice_phone: null,
  invoice_company_name: null,
  invoice_nip: null,
  invoice_street: null,
  invoice_postal_code: null,
  invoice_city: null,
  departure_type: null,
  departure_city: null,
  return_type: null,
  return_city: null,
  diet: null,
  diet_name: null,
  accommodation_request: null,
  selected_source: null,
  source_name: null,
  selected_addons: null,
  selected_protection: null,
  contract_status: null,
  contract_rejection_reason: null,
  qualification_card_status: null,
  qualification_card_rejection_reason: null,
  payment_plan: null,
};

